### ISSUE TITLE
Pact Consumer tests are failing starting with node 18.10 and 19

### ISSUE THREAD

**Issue by RaresAil** [pact-foundation/pact-js-core#431]
### Software versions

- **OS**: Ubuntu Boo OSX 10.11.5_
- **Pact Node version**:  Pact Foundation 10.3.1
- **Node Version**: 18.10.x, 19.x

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle

### Expected behaviour

All the tests to pass

### Actual behaviour

The tests fail after upgrading from node `18.8.0` to `18.10.0` even on `19.x`

### Steps to reproduce

Update to node 18.10 or 19 and run the Consumer tests

### Relevant log files

```
● Console

    console.error


      at Pact.Object.<anonymous>.Pact.verify (../node_modules/@pact-foundation/src/httpPact/index.ts:211:15)
      at Object.<anonymous> (../node_modules/jest-pact/dist/pactWith.js:12:45)

    console.error
      [31mPact verification failed![39m

      at Pact.Object.<anonymous>.Pact.verify (../node_modules/@pact-foundation/src/httpPact/index.ts:212:15)
      at Object.<anonymous> (../node_modules/jest-pact/dist/pactWith.js:12:45)

    console.error
      [31mTest failed for the following reasons:
      
        Mock server failed with the following mismatches:
      
      	0) The following request was expected but not received: 
      	    Method: POST
      	    Path: ...
      	    Headers:
      	      Accept: application/json
      	      Authorization: Bearer mock
      	      Content-Type: application/json
      	    Body: ...

      at Pact.Object.<anonymous>.Pact.verify (../node_modules/@pact-foundation/src/httpPact/index.ts:213:15)
      at Object.<anonymous> (../node_modules/jest-pact/dist/pactWith.js:12:45)

  ● Pact between .... returns the correct response

    socket hang up

      at Function.Object.<anonymous>.AxiosError.from (../node_modules/axios/lib/core/AxiosError.js:89:14)
      at RedirectableRequest.handleRequestError (../node_modules/axios/lib/adapters/http.js:533:25)
      at ClientRequest.eventHandlers.<computed> (../node_modules/follow-redirects/index.js:14:24)

  ● Pact between ... returns the correct response

    Pact verification failed - expected interactions did not match actual.

      at new VerificationError (../node_modules/@pact-foundation/pact/src/errors/verificationError.js:21:42)
      at Pact.Object.<anonymous>.Pact.verify (../node_modules/@pact-foundation/src/httpPact/index.ts:217:13)
      at Object.<anonymous> (../node_modules/jest-pact/dist/pactWith.js:12:45)

Failed to initialise global tracing subscriber - a global default trace dispatcher has already been set
```

**Comment by TimothyJones** [comment]
Are you giving the mock server an IP address or just localhost? I know that node 18 uses ipv6 by default, which can cause some confusion around what “localhost” means when communicating externally

**Comment by RaresAil** [comment]
I get the base url like this:

```js
instance.defaults.baseURL = provider.mockService.baseUrl;
```

**Comment by RaresAil** [comment]
@TimothyJones i tested and if i keep only 1 interaction per file it passes, from the debug logs it looks like pact is doing the cleanup too early

**Comment by mefellows** [comment]
Can you please provide a reproducible example? We test the builds on node 18 so I don't think the node version is the problem (it might be, but seems unlikely). It smells of incorrectly handled promises, but hard to tell from that output.

**Comment by RaresAil** [comment]
@mefellows i created a repo with the issue: https://github.com/RaresAil/issue-env-pact

**Comment by TimothyJones** [comment]
Your example works for me using node 18.10.0, but fails in the same way as your test with node 19.5.0.

**Comment by TimothyJones** [comment]
@mefellows My guess is that the core isn't waiting for the server to start duing `addInteraction`. I'll leave this for someone more qualified to look into.

**Comment by TimothyJones** [comment]
@RaresAil Did you get any further with this? I ran in to the same issue in an unrelated project that uses axios, but does not use Pact. I suspect axios might be at fault

**Comment by RaresAil** [comment]
> @RaresAil Did you get any further with this? I ran in to the same issue in an unrelated project that uses axios, but does not use Pact. I suspect axios might be at fault

I tried and with node-fetch and same issue what i did now as a workaround is the delay of 1 second

**Comment by TimothyJones** [comment]
> I tried and with node-fetch and same issue 

Aha. That points to the changing node version being the reason for the broken test. With this information, I was able to get to the bottom of it:

I checked the changelog - and one of the breaking changes in 19.x is that `Keep-Alive` is set to true on http connections. This is a problem on repeated tests, as at some point you will pick up a connection that is due to be closed soon. This also explains why your workaround of a one second pause works - as the default socket lifetime is 1 second.

You confirm this with `httpAgent: new http.Agent({ keepAlive: false }),` in your axios options (weirdly, if you're creating axios each time, then `new httpAgent({keepAlive: true})` will also work, because the connection pool won't be reused).

I think the right fix is to retry on `ECONNRESET`.

@mefellows This is a thing that could be changed in the proxy to avoid it in the future. If you want to do this, you can just add a bit of middleware that has `res.append('Connection', 'close');`

**Comment by RaresAil** [comment]
> 

Thank you, i will also change on my side from the delay of 1s to disable the keepAlive
